### ISSUE TITLE
导航不错，表示感谢

### ISSUE THREAD

**Issue by y377** [tojohnonly/PersonalNavigationWebsite#3]
![image](https://user-images.githubusercontent.com/58632405/97035765-64305200-1599-11eb-9d18-db19823380fd.png)
导航不错，表示感谢！
不过现在显示器都是宽屏，19，21，23，27等等，中间是不是有点太密了

**Comment by tojohnonly** [comment]
我这个是1080P的，没有适配带鱼屏，有兴趣可以学习下Html，代码很简单的…

**Comment by y377** [comment]
HTML略懂一二，今晚我就抽空来改下你的，这个是不是先fork才能更改？

**Comment by y377** [comment]
![image](https://user-images.githubusercontent.com/58632405/117546342-8cc2f980-b05c-11eb-9013-31c4b4e09d3a.png)
![image](https://user-images.githubusercontent.com/58632405/117546365-a19f8d00-b05c-11eb-8efb-af3e23d2b133.png)
一直说改，一直没改，这两天没事，我改好了，完美适配手机，我也不会提交新请求，就在这里说明一下，需要源码的同学回头我再发来（正在备案中，故无法访问）
#### 说明&改动
1. 删减原作者所有硬标签（HTML&css）并采用bootstrapV4框架
2. 保留原作者输入栏然后手动JavaScript代码（且新增bing）
3. 新增顶部自动日期（JavaScript）
4. 新增底部（footer）自动年份（JavaScript）
5. **输入框后面一键删除文字功能**（bootstrap的功劳）
6. 优化了当使用安卓手机在输入框准备输入内容时，安卓键盘会将底部“footer”内容顶上来的bug，虽不影响使用，但不美观
7. [demo](https://demo.navigation.heyun.vip/)
