### ISSUE TITLE
使用uni-app重构了一遍

### ISSUE THREAD

**Issue by RC-CHN** [tojohnonly/PersonalNavigationWebsite#4]
你好！最近我在家里部署了很多服务，记住他们的端口号也不再是件容易事了。于是我以本仓库为基础，使用uni-app重构了本页面
你可以在https://gitee.com/Ruochen-Pan/my-navigation
看到我的重构

**Comment by RC-CHN** [comment]
![QQ图片20211011171842](https://user-images.githubusercontent.com/67079377/136765784-c93b6a0d-d0d2-4d7f-ab67-6e90613ba84c.jpg)
![QQ图片20211011171907](https://user-images.githubusercontent.com/67079377/136765823-3b58b07c-bde0-48b0-9e07-49ba484a437b.jpg)
对移动端自适应

**Comment by tojohnonly** [comment]
bingo🦄
